# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VManga' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VManga
	pod 'Alamofire', '~> 4.4'
pod 'SwiftyJSON'
pod 'RAMAnimatedTabBarController', "~> 2.0.13" 

end
